### ISSUE TITLE
wasm build

### ISSUE THREAD

**Issue by caperaven** [nu-book/zxing-cpp#139]
I am having some issues building the web assembly wrapper.
I get a "FileNotFoundError: [WinError 2] The system cannot find the file specified" error

```
<path to wrapper>emcmake cmake
configure: cmake -DCMAKE_TOOLCHAIN_FILE=<path to emscripten>\cmake\Modules\Platform\Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="<path to emscripten>/emsdk/node/12.18.1_64bit/bin/node.exe" -G MinGW Makefiles
Traceback (most recent call last):
  File "<path to emscripten>\emsdk\upstream\emscripten\\emcmake.py", line 34, in <module>
    sys.exit(run())
  File "<path to emscripten>\emsdk\upstream\emscripten\\emcmake.py", line 27, in run
    building.configure(sys.argv[1:])
  File "<path to emscripten>\emsdk\upstream\emscripten\tools\building.py", line 357, in configure
    run_process(args, stdout=stdout, stderr=stderr, env=env, **kwargs)
  File "<path to emscripten>\emsdk\upstream\emscripten\tools\shared.py", line 191, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 472, in run
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 775, in __init__
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 1178, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

When running the command emcmake cmake command.

I am not very experienced in this area.  
I did notice that the c files referred to header files that are not there. Not sure if that makes a difference or not.
Can anyone assist me in getting this to build or perhaps point me in a direction where I can perhaps downloaded the last release compiled versoin?

**Comment by axxel** [comment]
I'm not an expert in emscripten either but managed to build it on my development machine and the CI system with the commands outlined in the Readme. Have not tested it on windows, though. Could you try again with the following command line run inside an empty directory:
```bash
emcmake cmake <path to zxing-cpp.git/wrappers/wasm>
```

There is unfortunatelly currently no download link available the latest version. You can extract an older wasm binary from the live demo (see Readme).

**Comment by axxel** [comment]
You can now find the latest build result on the "Actions" page, e.g. [here](https://github.com/nu-book/zxing-cpp/actions/runs/181374220).

Any progress on building it your own?

**Comment by axxel** [comment]
Due to lack of feedback and since there is now the possibility to download the latest build from the CI system, I close this issue.
