### ISSUE TITLE
Couldn't install zxing-cpp lib with pip in python project

### ISSUE THREAD

**Issue by bestpower** [nu-book/zxing-cpp#357]
OS：Windows 10 x64
Python version：3.6.8
Pip version：21.3.1

Bug Info:
1.git clone https://github.com/nu-book/zxing-cpp.git
2.cd zxing-cpp\wrappers\python
3.run "pip install zxing-cpp" in cmd
4.Output these error infos:
```txt
WARNING: Ignoring invalid distribution -ip (d:\developtools\sdk\python\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\developtools\sdk\python\lib\site-packages)
Collecting zxing-cpp
  Using cached zxing-cpp-1.4.0.tar.gz (8.1 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in d:\developtools\sdk\python\lib\site-packages (from zxing-cpp) (1.17.4)
Building wheels for collected packages: zxing-cpp
  Building wheel for zxing-cpp (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\developtools\sdk\python\python.exe' 'd:\developtools\sdk\python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\***\AppData\Local\Temp\tmp73c4gbo6'
       cwd: C:\Users\***\AppData\Local\Temp\pip-install-pyva2qis\zxing-cpp_48c405a7160e470384e6b934a094ca25
  Complete output (68 lines):
  running bdist_wheel
  running build
  running build_ext
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:2 (project):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.


  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/***/AppData/Local/Temp/pip-install-pyva2qis/zxing-cpp_48c405a7160e470384e6b934a094ca25/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "d:\developtools\sdk\python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "d:\developtools\sdk\python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "d:\developtools\sdk\python\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 262, in build_wheel
      metadata_directory)
    File "C:\Users\***\AppData\Local\Temp\pip-build-env-0sqx3ovw\overlay\Lib\site-packages\setuptools\build_meta.py", line 231, in build_wheel
      wheel_directory, config_settings)
    File "C:\Users\***\AppData\Local\Temp\pip-build-env-0sqx3ovw\overlay\Lib\site-packages\setuptools\build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\***\AppData\Local\Temp\pip-build-env-0sqx3ovw\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 82, in <module>
      zip_safe=False,
    File "C:\Users\***\AppData\Local\Temp\pip-build-env-0sqx3ovw\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "d:\developtools\sdk\python\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "d:\developtools\sdk\python\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "d:\developtools\sdk\python\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\***\AppData\Local\Temp\pip-build-env-0sqx3ovw\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "d:\developtools\sdk\python\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "d:\developtools\sdk\python\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "d:\developtools\sdk\python\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "d:\developtools\sdk\python\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "d:\developtools\sdk\python\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\***\AppData\Local\Temp\pip-build-env-0sqx3ovw\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "d:\developtools\sdk\python\lib\distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "d:\developtools\sdk\python\lib\distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "d:\developtools\sdk\python\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "setup.py", line 41, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp)
    File "d:\developtools\sdk\python\lib\subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\wangyu\\AppData\\Local\\Temp\\pip-install-pyva2qis\\zxing-cpp_48c405a7160e470384e6b934a094ca25', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\wangyu\\AppData\\Local\\Temp\\pip-install-pyva2qis\\zxing-cpp_48c405a7160e470384e6b934a094ca25\\build\\lib.win-amd64-3.6', '-DPYTHON_EXECUTABLE=d:\\developtools\\sdk\\python\\python.exe', '-DVERSION_INFO=1.4.0', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\wangyu\\AppData\\Local\\Temp\\pip-install-pyva2qis\\zxing-cpp_48c405a7160e470384e6b934a094ca25\\build\\lib.win-amd64-3.6', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for zxing-cpp
Failed to build zxing-cpp
ERROR: Could not build wheels for zxing-cpp, which is required to install pyproject.toml-based projects
WARNING: Ignoring invalid distribution -ip (d:\developtools\sdk\python\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\developtools\sdk\python\lib\site-packages)
```

How to fix?

**Comment by axxel** [comment]
A bit of googling suggest that you simply don't have a c/c++ compiler installed on your system. Please install the latest Visual Studio Community Edition and try again.

**Comment by bestpower** [comment]
I have installed the cmake-gui tools into the win10 os and it's no help to install this python pkg, for this reason, I changed the os to linux(Ubuntu) and installed success directly, Thanks.

**Comment by axxel** [comment]
You already had a working `cmake` setup but seemingly no c++ compiler, so installing cmake-gui tools did not help for sure. I'll add a comment to the README pointing out these requirements.
